# Generated by Django 5.1.7 on 2025-03-29 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Theater', 'Theater'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('concert', 'Concert'), ('wedding', 'Wedding'), ('corporate', 'Corporate Event')], max_length=50)),
                ('event_description', models.TextField()),
                ('event_theme', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('setup_time', models.DateTimeField()),
                ('breakdown_time', models.DateTimeField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('regular', 'Regular'), ('early_bird', 'Early Bird'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='regular', max_length=20)),
                ('ticket_description', models.TextField()),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vvip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_quantity', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('min_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField()),
                ('early_bird_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organizers.event')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('av', 'AV Equipment'), ('decor', 'Decor'), ('entertainment', 'Entertainment'), ('security', 'Security'), ('printing', 'Printing'), ('transportation', 'Transportation'), ('waste_management', 'Waste Management')], max_length=20)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=255)),
                ('transportation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_schedule', models.TextField()),
                ('passenger_capacity', models.IntegerField()),
                ('special_requests', models.TextField()),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_personnel_count', models.IntegerField()),
                ('security_duties', models.TextField()),
                ('security_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_requirements', models.TextField()),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_materials', models.TextField()),
                ('printing_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('design_requirements', models.TextField()),
                ('delivery_timeframe', models.DateTimeField()),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_entertainment', models.CharField(max_length=255)),
                ('entertainment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performance_duration', models.DurationField()),
                ('special_requirements', models.CharField(blank=True, max_length=255)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_theme', models.CharField(max_length=255)),
                ('items_supplied', models.TextField()),
                ('decor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_time', models.TimeField()),
                ('return_tear_down_time', models.TimeField()),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering_type', models.CharField(max_length=100)),
                ('menu_options', models.TextField()),
                ('dietary_preferences', models.CharField(blank=True, max_length=255)),
                ('catering_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_requirements', models.CharField(blank=True, max_length=255)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='AV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_provided', models.CharField(max_length=255)),
                ('av_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('technical_support', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('setup_time', models.TimeField()),
                ('contact_emergency', models.CharField(max_length=15)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_address', models.CharField(max_length=255)),
                ('venue_capacity', models.IntegerField()),
                ('venue_booking_time', models.DateTimeField()),
                ('venue_rental_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venue_requirements', models.TextField(blank=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_types_collected', models.TextField()),
                ('waste_management_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_details', models.TextField()),
                ('restroom_facilities', models.TextField()),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.vendor')),
            ],
        ),
    ]
