# Generated by Django 5.1.4 on 2025-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='transport_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
