# Generated by Django 5.1.7 on 2025-03-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
